arduino = Arduino(desktop=True)

@block
def func():
    print_i(1)
    print_i(2)
    print_i(3)
    print_i(4)
    print_i(5)
    print_i(6)
    print_i(7)
    print_i(8)
    print_i(9)
    print_i(10)
    print_i(12)
    print_i(13)
    print_i(14)
    print_i(15)
    print_i(1)
    print_i(2)
    print_i(3)
    print_i(4)
    print_i(5)
    print_i(6)
    print_i(7)
    print_i(8)
    print_i(9)
    print_i(10)
    print_i(12)
    print_i(13)
    print_i(14)
    print_i(15)
    die(0)
    
arduino.send(func)
